### PR TITLE
fix: update getOffset (fix #849)

### LINKED ISSUE #849: Cannot read property 'offsetTop' of null
## Describe the bug
React-Editor put in Modal from material-ui triggers a `Cannot read property 'offsetTop' of null` when using Toolbar

## Expected behavior
Toolbar & ContextMenu should work

## Additional context
When Editor is in Portal or Modal component, the `getOffset` loop never reach the end condition `while (element !== document.body) ` 
because of `element.offsetParent` which is not `document.body` for Modal Components.

### PR DESCRIPTION
**Pull request by dbuchet**
### Please check if the PR fulfills these requirements
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's the right issue type on the title
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description
Update loop-end condition to work when Editor is in Modal or Portal

Description
Related issue: #849 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/editor/src/js/utils/dom.js [hunk 1]
```diff
@@ -1234,7 +1234,7 @@ function getOffset(element) {
   while (element !== document.body) {
     top += element.offsetTop;
     left += element.offsetLeft;
-    element = element.offsetParent;
+    element = element.offsetParent || element.parentElement;
   }
```
Comment (seonim-ryu) [inline apps/editor/src/js/utils/dom.js]: I think it can be solved by modifying with the `do-while` statement as below. Can you check it?

```js
do {
  top += element.offsetTop || 0;
  left += element.offsetLeft || 0;
  element = element.offsetParent;
} while (element);
```

Comment (dbuchet) [reply apps/editor/src/js/utils/dom.js]: Sure it works :)
