### PR TITLE
fix: not insert data-tomark-pass when img tag has src (fix: #502)

### LINKED ISSUE #502: img tag with style is converted markdown syntax (2MD)
## Version
v1.4.0

## Test Environment
Chrome

## Current Behavior

``` html
<img src="https://user-images.githubusercontent.com/1215767/34336735-e7c9c4b0-e99c-11e7-853b-2449b51f0bab.png" height="20px">
```

If this tag is inserted in markdown, it is changed markdown syntax after change mode.

``` md
![](https://user-images.githubusercontent.com/1215767/34336735-e7c9c4b0-e99c-11e7-853b-2449b51f0bab.png)
```

## Expected Behavior

`` should be maintained.

### PR DESCRIPTION
**Pull request by sohee-lee7**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

fix #502

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/convertor.js [hunk 1]
```diff
@@ -105,7 +105,7 @@ class Convertor {
    * @returns {string} html text
    */
   _markdownToHtml(markdown, env) {
-    markdown = markdown.replace(/<([^/>]+)([/]?)>/g, '<$1 data-tomark-pass $2>');
+    markdown = markdown.replace(/<([^>]+)([/]?)>/g, '<$1 data-tomark-pass $2>');
```
Comment (dongwoo-kim) [inline src/js/convertor.js]: 버그 픽스라면.. 테스트 코드가 추가되어야 할 것 같습니다.

Comment (sohee-lee7) [reply src/js/convertor.js]: 앗. 넵!
