### PR TITLE
fix: Fixed autofocus={false} invalid (fix #1945)

### LINKED ISSUE #1945: editor is still getting focused after autofocus=false
## Describe the bug
```js
<Editor autofocus={false}/>
```
Then also editor is getting focused after load
## To Reproduce
Clone this repo https://github.com/ats1999/editor-no-chakra-UI and run the example.

## Expected behaviour
Editor should not get focused

## Screenshots

https://user-images.githubusercontent.com/54087826/138985006-ef62f51f-c222-4c82-a44a-4049a346fae2.mp4

### PR DESCRIPTION
**Pull request by zhousg**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description
Modify the issue in which the `autofocus` option is ignored in the markdown tab mode
* related issue(#1802)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/editor/src/markdown/mdEditor.ts [hunk 1]
```diff
@@ -73,15 +75,19 @@ export default class MdEditor extends EditorBase {
     this.commands = this.createCommands();
     this.specs.setContext({ ...this.context, view: this.view });
     this.createClipboard();
-    this.eventEmitter.listen('changePreviewTabWrite', () => this.toggleActive(true));
+    this.eventEmitter.listen('changePreviewTabWrite', (isMounted) =>
```
Comment (js87zz) [inline apps/editor/src/markdown/mdEditor.ts:78]: Overall, `isMarkdownTabMounted` seems to be more readable than `isMounted`.

**Review by js87zz — CHANGES_REQUESTED** [review]
Thanks for contributing!!
It will be merged after applying the code review and the final test. Thank you.

**Review by js87zz — APPROVED** [review]
