### PR TITLE
fix: change types from button to toolbarButton (fix #750)

### LINKED ISSUE #750: Remove 'JQuery' from custom toolbar
## Version
1.4.10

## Development Environment
none

## Current Behavior
JQuery must be used when writing custom toolbar

```js
  interface IButtonOptions {
    className: string;
    $el: JQuery; // change or add 'HTMLElement'
    command?: string;
    event?: string;
    text?: string;
    tooltip?: string;
    style?: string;
    state?: string;
  }
```

## Expected Behavior
Remove 'JQuery' from custom toolbar
or add 'HTMLElement' if possible.

### PR DESCRIPTION
**Pull request by seonim-ryu**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

* Related issue #750

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/editor/index.d.ts [hunk 1]
```diff
@@ -226,17 +208,15 @@ declare namespace toastui {
...
-    public insertItem(index: number, item: ToolbarItem | ButtonItem | string): void;
+    public insertItem(index: number, item: ToolbarItem | ToolbarButton | string): void;
 
     public indexOfItem(item: ToolbarItem): number;
 
     public removeItem(item: ToolbarItem | number, destroy?: boolean): ToolbarItem | undefined;
 
     public removeAllItems(): void;
-
-    public addButton(button: Button, index?: number): void;
```
Comment (seonim-ryu) [inline apps/editor/index.d.ts]: `addButton()` 메서드 제거됨 (1.x에서 디프리케이트)

File: apps/editor/src/js/ui/toolbarButton.js [hunk 2]
```diff
@@ -6,17 +6,27 @@
...
+ * @typedef {object} toolbarButtonOptions
+ * @property {HTMLElement} el - target element
+ * @property {string} className - button's class name
+ * @property {string} command - command name to execute on click
+ * @property {string} event - event name to trigger on click
+ * @property {string} text - text on button
+ * @property {string} tooltip - text on tooltip
+ * @property {string} style - button's style
+ * @property {string} state - button's state
+ */
```
Comment (seonim-ryu) [inline apps/editor/src/js/ui/toolbarButton.js]: `@toast-ui/doc`에서 네스티드 객체인 경우 파싱을 못하고 있어서 jsodc을 분리함. 추후 개선 사항으로 진행

**Comment by ryum91** [comment]
감사합니다 ~ !
