### PR TITLE
fix: XSS Vulnerability using anchor tags (fix #628)

### LINKED ISSUE #628: XSS Vulnerability using anchor tags
## Version

The one present in example [page](https://nhn.github.io/tui.editor/api/latest/tutorial-example02-editor-basic.html#), also happening on latest (1.4.6), probably any tui editor with html enabled

## Test Environment

Chrome Version 79.0.3909.0 (Official Build) canary (64-bit)
MacOS 10.14.6

## Current Behavior

Enter in editor:
```html
<a href="javascript:alert(document.cookie)"> text </a>
```
When you clicked on previewed link, alert will pop up with browser cookies (if have any). You can also put `window.localStorage` or other malicious actions

## Expected Behavior

Output is properly sanitised

### PR DESCRIPTION
**Pull request by LunaTK**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

* Add HTML attribute black list RegEx in `htmlSanitizer`

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/htmlSanitizer.js [hunk 1]
```diff
@@ -28,6 +28,10 @@ const SVG_ATTR_LIST_RX = new RegExp('^(accent-height|accumulate|additive|alphabe
     'width|widths|x|x-height|x1|x2|xlink:actuate|xlink:arcrole|xlink:role|xlink:show|xlink:title|' +
     'xlink:type|xml:base|xml:lang|xml:space|xmlns|xmlns:xlink|y|y1|y2|zoomAndPan)', 'g');
 
+const ATTR_VALUE_BLACK_LIST_RX = {
+  'href': new RegExp('^(javascript:).*', 'g')
+};
```
Comment (seonim-ryu) [inline src/js/htmlSanitizer.js]: I think you'll have to deal with all three of the following cases.
```html
<object data='data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoIlhTUyIpPg=='></object>
<embed src="data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoIlhTUyIpPg=="></embed>
<a href=javascript:alert(document.domain)>hello</a>
```

File: src/js/htmlSanitizer.js [hunk 2]
```diff
@@ -28,6 +28,10 @@ const SVG_ATTR_LIST_RX = new RegExp('^(accent-height|accumulate|additive|alphabe
     'width|widths|x|x-height|x1|x2|xlink:actuate|xlink:arcrole|xlink:role|xlink:show|xlink:title|' +
     'xlink:type|xml:base|xml:lang|xml:space|xmlns|xmlns:xlink|y|y1|y2|zoomAndPan)', 'g');
 
+const ATTR_VALUE_BLACK_LIST_RX = {
+  'href': new RegExp('^(javascript:).*', 'g')
```
Comment (seonim-ryu) [inline src/js/htmlSanitizer.js]: Our convention is that regular expressions use the literal instead of the constructor function.
```js
var regExp = /foo/g;
```

File: src/js/htmlSanitizer.js (hunk 1 above)
Comment (LunaTK) [reply src/js/htmlSanitizer.js]: This also works

```html
<object data='data:text/html;base64,PGltZyBzcmM9Ii8xLnBuZyIgb25lcnJvcj1hbGVydCgiWFNTIik+'></object>
```
**base64 decoded**
```html
PGltZyBzcmM9Ii8xLnBuZyIgb25lcnJvcj1hbGVydCgiWFNTIik+
<img src="/1.png" onerror=alert("XSS")>
```

It would be more robust if `object` and `embed` also sanitize element they are rendering, if it is `html`.

File: src/js/htmlSanitizer.js [hunk 3]
```diff
@@ -82,6 +87,24 @@ function leaveOnlyWhitelistAttribute($html) {
   });
 }
 
+/**
+ * Remove invalid attribute values
+ * @private
+ * @param {jQuery} $html jQuery instance
+ */
+function removeInvalidAttributeValues($html) {
+  $html.find('*').each((index, node) => {
```
Comment (seonim-ryu) [inline src/js/htmlSanitizer.js]: I think it's unreasonable to navigate all nodes. You can only handle tags that have property values ​​that can cause XSS.

File: test/unit/htmlSanitizer.spec.js [hunk 4]
```diff
@@ -41,5 +41,13 @@ describe('htmlSanitizer', function() {
       expect($circle.attr('stroke-width')).toBeTruthy();
       expect($circle.attr('fill')).toBeTruthy();
     });
+
+    it('Remove attributes with invalid value', function() {
+      expect(htmlSanitizer('<a href="javascript:alert();">xss</a>', true)).toEqual('<a>xss</a>');
```
Comment (seonim-ryu) [inline test/unit/htmlSanitizer.spec.js]: If you want to compare the value of primitive type, we recommend using `toBe`.

File: src/js/htmlSanitizer.js (hunk 1 above)
Comment (seonim-ryu) [reply src/js/htmlSanitizer.js]: @LunaTK
You're right. It's missing from the code. You can add that tag [here](https://github.com/nhn/tui.editor/blob/master/src/js/htmlSanitizer.js#L57).

Comment (LunaTK) [reply src/js/htmlSanitizer.js]: @seonim-ryu 
I checked [Github's Specification](https://github.github.com/gfm/#html-block) about rendering raw HTML to see how Github renders `embed` and `object` tags.

Github only treats following tags as valid tag. Otherwise, it seems renderer just **unwrap the invalid tag** and render child elements.

> Start condition: line begins the string `<` or `</` followed by one of the strings (case-insensitive) `address`, `article`, `aside`, `base`, `basefont`, `blockquote`, `body`, `caption`, `center`, `col`, `colgroup`, `dd`, `details`, `dialog`, `dir`, `div`, `dl`, `dt`, `fieldset`, `figcaption`, `figure`, `footer`, `form`, `frame`, `frameset`, `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `head`, `header`, `hr`, `html`, `iframe`, `legend`, `li`, `link`, `main`, `menu`, `menuitem`, `nav`, `noframes`, `ol`, `optgroup`, `option`, `p`, `param`, `section`, `source`, `summary`, `table`, `tbody`, `td`, `tfoot`, `th`, `thead`, `title`, `tr`, `track`, `ul`, followed by whitespace, the end of the line, the string `>`, or the string `/>`.


To summarize, **[GFM](https://github.github.com/gfm/#raw-html) does not allow** `embed` and `object` tags to be rendered.

Since `tui-editor` claims that it follows GFM, **unwrapping** invalid HTML tags seems to be more appropriate.

However, current policy of `tui-editor`'s sanitizer for invalid tags is to **remove** them, including their child elements.
https://github.com/nhn/tui.editor/blob/01e83e63ddeb5ab7987027513c49be5319773d82/src/js/htmlSanitizer.js#L38-L49


So what do you want me to do?
1. Unwrap
2. Remove


> @LunaTK
> You're right. It's missing from the code. You can add that tags [here](https://github.com/nhn/tui.editor/blob/master/src/js/htmlSanitizer.js#L57).


Do you want to `remove` them?

Comment (seonim-ryu) [reply src/js/htmlSanitizer.js]: @LunaTK
Yes, **remove** them.

Once our basic policy is to follow GFM. However, depending on the situation, the spec is changed and used. According to the current editor's spec, it should be removed.

Issue that follow the GFM specification you mentioned will be registered as features and reviewed later.

**Comment by seonim-ryu** [comment]
@LunaTK 
Can you tell me how long you can apply your modified code? The editor v1.4.7 will be released soon, but it would be nice to include your PR if possible. :)

**Comment by LunaTK** [comment]
@seonim-ryu
I will try to finish it today!

File: test/unit/htmlSanitizer.spec.js (hunk 4 above)
Comment (LunaTK) [reply test/unit/htmlSanitizer.spec.js]: https://github.com/nhn/tui.editor/blob/7407f58dd979df066b20144b7f4925e514a2b272/test/unit/htmlSanitizer.spec.js#L12

Do you want me to fix this also?

Comment (seonim-ryu) [reply test/unit/htmlSanitizer.spec.js]: @LunaTK Yes, you can fix it together.

**Comment by LunaTK** [comment]
@seonim-ryu 
I resolved all conversations.
May I ask you what do you mean by “modify added comments”?

Thank you for your review :)

**Comment by seonim-ryu** [comment]
@LunaTK 
> If you modify the added comments ...

It meant my comment on the question below. 😅
> https://github.com/nhn/tui.editor/blob/7407f58dd979df066b20144b7f4925e514a2b272/test/unit/htmlSanitizer.spec.js#L12
> 
> Do you want me to fix this also?

Merging PR will go on tomorrow. Thank you so much.

**Comment by LunaTK** [comment]
@seonim-ryu 
Missed upper case attribute values.
Fixed it so that attribute values are tested after calling toLowerCase().

**Comment by seonim-ryu** [comment]
@LunaTK 
Good! I checked it. I'll merge. 👍
