### PR TITLE
fix: fixed addImageBlobHook error in wwEditor (fixes: #2053)

### LINKED ISSUE #2053: addImageBlobHook only fires in Markdown-Mode
## Describe the bug
The addImageBlobHook only fires in Markdown-Mode depending on the contents of the ClipboardEvent. In the earlier version of the editor we used (v2.x), this worked just fine.

## To Reproduce
1. Define a hook via config of the editor:
```ts
hooks: {
    addImageBlobHook: () => console.log('image blob hook!'),
} as HookMap,
```
2. Paste image first in markdown mode, then in WYSIWYG mode

**Event only fires in Markdown-Mode!**

## Expected behavior
Event should fire in both modes for being able to intercept images being pasted.

## Additional context
- the event DOES fire when a file is copied, however it DOES NOT fire when the contents of an image are copied (eg, right click -> copy image in browser)
- we use the vue-wrapper
- Pull-request to solve the issue will follow right after
- see our full config below

```ts
return {
	height: this.initialHeight,
	minHeight: this.initialHeight,
	language: this.$i18n.locale.substr(0, 2),
	useCommandShortcut: true,
	usageStatistics: false,
	hideModeSwitch: false,
	placeholder: this.placeholder,
	toolbarItems: [
		['heading'],
		['bold', 'italic', 'strike'],
		['hr', 'quote'],
		['ul', 'ol', 'task'],
		['table', 'link'],
		['code', 'codeblock'],
		['scrollSync'],
	] as any,
	linkAttributes: {
		target: '_blank',
		rel: 'noopener noreferrer'
	} as LinkAttributes,
	hooks: {
		addImageBlobHook: () => console.log('image blob hook!'),
	} as HookMap,
} as EditorOptions;
```

### PR DESCRIPTION
**Pull request by Isitar**
fixes #2053

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

this changes the code in wwEditor to align with the code in mdEditor

### CODE REVIEW

**Comment by Isitar** [comment]
The problem got introduced in https://github.com/nhn/tui.editor/commit/8d434ce7f596c3c901833e287f9cb845c0ead557

I understand if you don't like  the if (items) but the strict comparison of the length property simply breaks this feature.
you can maybe change all `if (items)` to `if (items?.length > 0)` but if you do, please keep it consistent in all editors (md, ww, etc.)

File: apps/editor/src/wysiwyg/wwEditor.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ export default class WysiwygEditor extends EditorBase {
             (ev as ClipboardEvent).clipboardData || (window as WindowWithClipboard).clipboardData;
           const items = clipboardData?.items;
 
-          if (items?.length === 1) {
+          if (items) {
```
Comment (js87zz) [inline apps/editor/src/wysiwyg/wwEditor.ts:174]: In this case, data pasted from ms words and ms excel are inserted as images. 
Can you check the condition again and fix it so that they only work for images?

Comment (Isitar) [reply apps/editor/src/wysiwyg/wwEditor.ts:174]: shouldn't the next line (`const imageBlob = pasteImageOnly(items);`) take care of that?

Comment (js87zz) [reply apps/editor/src/wysiwyg/wwEditor.ts:174]: Sorry for the late response. 
In the case of ms word, not only `text/html` and `text/plain` but also data in the image format are stored in the clipboard.
Therefore, `items?.length === 1` is added and this condition is not present, an issue arises in which ms word text is pasted as an image regardless of the next line(`const imageBlob = pasteImageOnly(items); `). However, this condition raises an another issue(#2053) you wrote.

Could you look at this problem in more detail and solve it?

Comment (Isitar) [reply apps/editor/src/wysiwyg/wwEditor.ts:174]: i analyzed it a bit further:

if you copy from word / excel, you get **4** Items in your clipboard:

- text/plain the plaintext representation of the table
- text/html the html representation (html tags)
- text/rtf the rtf representation
- image/png the png file for the table


if you copy an image from google you get **2** items:

- text/html the html code to embedd the image ()
- image/png the png file

Here is some test-code you can play with:
```
<body>
  <ul id="cb-data">

  </ul>

  <script>
    const b = document.querySelector('body');
    const ul = document.querySelector('#cb-data');
    b.addEventListener('paste', (ev) => {

      while (ul.firstChild) {
        ul.removeChild(ul.lastChild);
      }


      for (var i = 0; i < ev.clipboardData.items.length; i++) {
        const item = ev.clipboardData.items[i];
        const li = document.createElement('li');
        li.innerHTML = "... items[" + i + "].kind = " + item.kind + " ; type = " + item.type;
        if (item.kind === "string") {
          item.getAsString(data => {
            const liul = document.createElement('ul');
            const liulli = document.createElement('li');
            liulli.innerHTML = data;
            liul.appendChild(liulli);
            li.appendChild(liul);
          });
        }
        ul.appendChild(li)
      }
    });
  </script>
</body>
```

Comment (Isitar) [reply apps/editor/src/wysiwyg/wwEditor.ts:174]: I added a new code to detect ms office copy data

File: apps/editor/src/markdown/mdEditor.ts [hunk 2]
```diff
@@ -96,9 +96,18 @@ export default class MdEditor extends EditorBase {
...
       if (items) {
-        const imageBlob = pasteImageOnly(items);
+        let containsRtf = false;
+        for (var i = 0; i < items.length; i++) {
+          const item = items[i];
+          if (item.kind === 'string' && item.type === 'text/rtf') {
+            containsRtf = true;
+            break;
+          }
+        }
```
Comment (js87zz) [inline apps/editor/src/markdown/mdEditor.ts:106]: I think it would be simpler and readable to change it like below :)
```js
import { Transaction } from 'prosemirror-state';
import { EditorView } from 'prosemirror-view';
import { Fragment, Slice } from 'prosemirror-model';
import { ReplaceAroundStep } from 'prosemirror-transform';
import { MdPos, ToastMark } from '@toast-ui/toastmark';
// add below dependency
import toArray from 'tui-code-snippet/collection/toArray';

....
if (items) {
  const containRtfItem = toArray(items).some(item => item.kind === 'string' && item.type === 'text/rtf');
  ...
}
```

File: apps/editor/src/wysiwyg/wwEditor.ts [hunk 3]
```diff
@@ -171,13 +171,24 @@ export default class WysiwygEditor extends EditorBase {
...
-            const imageBlob = pasteImageOnly(items);
+          if (items) {
+            let containsRtf = false;
+            for (var i = 0; i < items.length; i++) {
+              const item = items[i];
+              if (item.kind === 'string' && item.type === 'text/rtf') {
+                containsRtf = true;
+                break;
+              }
+            }
```
Comment (js87zz) [inline apps/editor/src/wysiwyg/wwEditor.ts:182]: I think it would be simpler and readable to change it like below :)
```js
import { EditorView, NodeView } from 'prosemirror-view';
import { Node as ProsemirrorNode, Slice, Fragment, Mark, Schema } from 'prosemirror-model';
import isNumber from 'tui-code-snippet/type/isNumber';
// add below dependency
import toArray from 'tui-code-snippet/collection/toArray';

....
if (items) {
  const containRtfItem = toArray(items).some(item => item.kind === 'string' && item.type === 'text/rtf');
  ...
}
```

**Review by js87zz — APPROVED** [review]
I checked that it was working well. :)
I'd appreciate it if you check out reviews and reflect them. And please execute "git rebase" based on master branch.
After then, I will merge this PR. Thank you! 👍

File: apps/editor/src/markdown/mdEditor.ts (hunk 2 above)
Comment (Isitar) [reply apps/editor/src/markdown/mdEditor.ts]: ah didn't know you have a toArray helper, changed and pushed

**Comment by Isitar** [comment]
alright, i adjusted the code with toArray, ready to merge?

**Review by js87zz — APPROVED** [review]
I checked all the modification, and I fixed the simple lint error. 
When other features are developed, they will be released together.
Thank you! 👍

**Comment by js87zz** [comment]
@Isitar 
Thanks! I added it. :)
https://github.com/nhn/tui.editor/releases/tag/editor%403.1.3
