### PR TITLE
fix: scroll move to the top when change text color (fix: #569)

### LINKED ISSUE #569: scroll move to top when change text color
## Version
v1.4.3

## Test Environment
**Windows IE11**

## Current Behavior

Screen Recording 2019-07-09 at 10 46 31 AM mov

When change text color, scroll move top.

## Expected Behavior

Scroll should not be moved.

### PR DESCRIPTION
**Pull request by sohee-lee7**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

fix #569 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/extensions/colorSyntax.js [hunk 1]
```diff
@@ -101,6 +103,12 @@ function colorSyntaxExtension(editor) {
 
         const sq = wwe.getEditor();
         const tableSelectionManager = wwe.componentManager.getManager('tableSelection');
+
+        // Cache scrollTop before change text color.
+        // Because scrollTop is set 0 when focus() is called.
+        // focus() is called when change text color.
+        lastScrollTop = sq.getRoot().parentNode.scrollTop;
```
Comment (junghwan-park) [inline src/js/extensions/colorSyntax.js]: `sq.getRoot().parentNode.scrollTop`이 부분을 별도 함수로 분리하면 어떨까요?

Comment (junghwan-park) [reply src/js/extensions/colorSyntax.js]: `getScrollTopForReFocus()`

Comment (sohee-lee7) [reply src/js/extensions/colorSyntax.js]: 아하 함수로 분리하는게 좋겠네요 +_+ 감사합니다 👍
