### PR TITLE
fix: prevent to remove heading tag when press the enter key(fix #872)

### LINKED ISSUE #872: WYSIWYG Mode: Enter key deletes line unexpectedly
This editor looks amazing!  I was playing around with the WYSIWYG editor in your published examples and noticed behavior that made me pause... if you set your cursor at the very beginning of a line (I chose the "Header 4" line) and press the enter key it will simply delete that line.  I (and probably almost anyone) would have expected the editor to insert a blank line in the line above.  This makes me not "trust" the WYSIWYG editor for serious editing.  I'm on latest Chrome Windows 10.

### PR DESCRIPTION
**Pull request by js87zz**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description
* related issue(#872)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/editor/src/js/wwHeadingManager.js [hunk 1]
```diff
@@ -120,8 +120,8 @@ class WwHeadingManager {
     const element = domUtils.createElementWith('<div><br></div>');
 
     domUtils.insertBefore(
-      domUtils.getParentUntil(range.startContainer, this.wwe.getBody()),
-      element
+      element,
+      domUtils.getParentUntil(range.startContainer, this.wwe.getBody())
     );
```
Comment (seonim-ryu) [inline apps/editor/src/js/wwHeadingManager.js:125]: `_insertEmptyBlockToPrevious` 테스트를 하는건 좀 무리일까요ㅎㅎ

**Comment by seonim-ryu** [comment]
[4/8] 리뷰 완료! 간단하게 처리되었네요 👍 타이틀에 이슈 번호만 추가해주시면 될 것 같습니다.
```
fix: prevent to remove heading tag when press the enter key (fix #872)
```
