### PR TITLE
fix: remove highlight from preview after firing blur event (fix #1093)

### LINKED ISSUE #1093: Highlighting remains in the preview area in the markdown editor after blur
## Describe the bug
Highlighting remains in the preview area in the markdown editor after blur.

## To Reproduce
1. Edit the text in the markdown editor.
2. Click outside the editor. (Focus out)

## Expected behavior
Highlighting should be removed.

## Screenshots
mde

## Desktop (please complete the following information):
 - OS: All
 - Browser All
 - Version 2.2.0

### PR DESCRIPTION
**Pull request by seonim-ryu**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

* Related issue #1093 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/editor/src/js/mdPreview.js [hunk 1]
```diff
@@ -89,6 +93,16 @@ class MarkdownPreview extends Preview {
     });
   }
 
+  _removeHighlight() {
+    if (this.cursorNodeId) {
+      const currentEl = this._getElementByNodeId(this.cursorNodeId);
```
Comment (lja1018) [inline apps/editor/src/js/mdPreview.js:98]:
```
const cursorNodeId = this.cursorNodeId;
if (cursorNodeId)
```
이건 어떨까요?

File: apps/editor/test/unit/mdPreview.spec.js [hunk 2]
```diff
@@ -165,3 +165,41 @@ describe('listen cursorActivity event', () => {
...
+
+    document.body.innerHTML = '';
+    document.body.appendChild(editorEl);
+    document.body.appendChild(previewEl);
+
+    const eventManager = new EventManager();
+    const convertor = new Convertor(eventManager);
+    const toastMark = new ToastMark();
+    const preview = new MarkdownPreview(previewEl, eventManager, convertor, { highlight });
+    const editor = new MarkdownEditor(editorEl, eventManager, toastMark);
```
Comment (lja1018) [inline apps/editor/test/unit/mdPreview.spec.js:186]: Line 58-69와 겹치는데 외부로 빼도 되지 않을까요?

File: apps/editor/src/js/mdPreview.js (hunk 1 above)
Comment (seonim-ryu) [reply apps/editor/src/js/mdPreview.js:98]: 한 줄이 더 늘어나기 때문에 같은 프로퍼티를 세 번 이상 사용하지 않는 경우에는 변수에 할당하지 않으려고 합니다ㅎ 요건 유지할게요~
