### PR TITLE
fix: brs in table are newlined (fix #680)

### LINKED ISSUE #680: When there are blank lines in front of the table, BRs in the cell are newlined.
## Version

v1.4.7

## Test Environment

All

## Current Behavior

1. Enter the table in WYSIWYG.
2. Add blank lines before the table.
3. Enter text in the cell data and enter newline.
4. If changeing to Markdown, BRs are newlined in the table.

wwe
mde

## Expected Behavior

The markdown value should look like this:

```markdown
<br>
<br>
| foo<br>bar |  |  |
| ------ | --- | --- |
|  |  |  |
|  |  |  |
|  |  |  |
```

### PR DESCRIPTION
**Pull request by seonim-ryu**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

* Issue related to #680 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/convertor.js [hunk 1]
```diff
@@ -239,11 +239,16 @@ class Convertor {
...
       const FIND_CODE_RX = /`[^`]*<br>[^`]*`/ig;
+      const FIND_BRS_BEFORE_TABLE = /^(<br>)+\|/ig;
+      const foundTable = FIND_TABLE_RX.test(line);
 
-      if (!FIND_CODE_RX.test(line) && !FIND_TABLE_RX.test(line)) {
+      if (!FIND_CODE_RX.test(line) && !foundTable) {
         line = line.replace(/<br>/ig, '<br>\n');
+      } else if (foundTable && FIND_BRS_BEFORE_TABLE.test(line)) {
+        const brs = line.match(FIND_BRS_BEFORE_TABLE)[0].replace(/<br>/ig, '<br>\n');
+        line = `${brs}${line.replace(FIND_BRS_BEFORE_TABLE, '')}`;
```
Comment (seonim-ryu) [inline src/js/convertor.js]: 정규식 3번 체크할 필요 없음

File: src/js/convertor.js [hunk 2]
```diff
@@ -239,11 +239,15 @@ class Convertor {
...
+      const FIND_TABLE_RX = /^(<br>)+\||\|[^|]*\|/ig;
       const FIND_CODE_RX = /`[^`]*<br>[^`]*`/ig;
+      const FIND_BRS_BEFORE_TABLE = /^(<br>)+\|/ig;
+      const foundTable = FIND_TABLE_RX.test(line);
 
-      if (!FIND_CODE_RX.test(line) && !FIND_TABLE_RX.test(line)) {
+      if (!FIND_CODE_RX.test(line) && !foundTable) {
         line = line.replace(/<br>/ig, '<br>\n');
+      } else if (foundTable) {
+        line = line.replace(FIND_BRS_BEFORE_TABLE, match => match.replace(/<br>/ig, '<br>\n'));
```
Comment (dongwoo-kim) [inline src/js/convertor.js]: if / else 문 순서가 바뀌면 좀 더 간단해질 것 같네요. (foundTable 변수도 필요 없을 것 같구요)
```js
if (FIND_TABLE_RX.test(line)) {
  line = line.replace(FIND_BRS_BEFORE_TABLE, match => match.replace(/<br>/ig, '<br>\n'));
} else if (!FIND_CODE_RX.test(line)) {
  line = line.replace(/<br>/ig, '<br>\n');
}
```
