### PR TITLE
fix: broken list in table when changed to markdown (fix #708)

### LINKED ISSUE #708: List inserted into table is broken when converted to markdown
## Version

v1.4.6 ~

## Test Environment

All

## Current Behavior

1. In WYSIWYG, add a table and lists in the cell.

wwe

2. When converting to Markdown, `<li>` tags disappear.

```md
| <ul><li>foo</li><li>bar</li></ul> | |
| --- | --- |
| <ol><li>foo</li><li>bar</li></ol> | |
```
```md
| <ul>* foo* bar</ul> | |
| --- | --- |
| <ol>* foo* bar</ol> | |
```

## Related Issue

> nhn/to-mark#36
> https://github.com/nhn/to-mark/pull/39/files#diff-5326222f837d36fd2bff476584c07621R112

The logic has changed. Do not simply protect the `<ul>` from being converted. The `<li>` must also be protected using the `data-tomark-pass` attribute in the editor.

## Expected Behavior

When changing Markdown and WYSIWYG, data should be maintained as shown below:

* Markdown

```md
| <ul><li>foo</li><li>bar<ul><li>baz</li></ul></li></ul> | |
| --- | --- |
| <ul><li>foo</li><li>bar<ul><li>baz</li></ul></li></ul> | |
```
* WYSIWYG (e.g. GitHub preview)
gfm

### PR DESCRIPTION
**Pull request by seonim-ryu**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

* Issue related to #708 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/wwListManager.js [hunk 1]
```diff
@@ -10,8 +10,8 @@ import domUtils from './domUtils';
 const FIND_LI_ELEMENT = /<li/i;
 const DIV_OR_LI = 'DIV,LI';
 const UL_OR_OL = 'OL,UL';
-const FIND_TD_ELEMNT = /(<td[^>]*>)(.*?)(<\/td>)/g;
-const FIND_UL_OR_OL_ELEMNT = /<(ul|ol)([^>]*)>(.*?)(<\/\1>)/g;
+const FIND_CELL_TAG_RX = /(<(?:th|td)[^>]*>)(.*?)(<\/(?:th|td)>)/g;
+const FIND_PREVENTED_TAG_RX = /<(ul|ol|li)([^>]*)>/g;
```
Comment (junghwan-park) [inline src/js/wwListManager.js]: 이름으로 `FIND_LIST_OR_LIST_ITEM_TAG_RX`는 어떨까요? ㅎㅎ 아직은 리스트 관련 요소들만 찾고 있기도하고, 사용하는 코드가 엄청 아래에 있는데 Prevented라는 이름이 어떤것들을 찾는것인지 직관적이지는 않은거 같아서요.

Comment (seonim-ryu) [reply src/js/wwListManager.js]: @junghwan-park
직관적이어서 좋네요 👍 변경하겠습니다.
