### PR TITLE
fix: mouseover always is registered (close: #473)

### LINKED ISSUE #473: Mouseover event handler is always registered
## Version
v1.3.3

## Test Environment
Chrome

`mouseover` event handler that is for table selection is always registered wherever `mousedown` event occur.

https://github.com/nhn/tui.editor/blob/6f76c7b5805478dc5e5e0fa35ccd387206a08138/src/js/wwTableSelectionManager.js#L146-L156

When `mousedown` event occur in the table, `selectionStart` is `<td>` element. Otherwise, `selectionStart` is `undefined` and don't register `mouseover` that is for table selection.

But currently `mouseover` event handler that is for table selection is always registered wherever `mousedown` event occur. So many `mouseover` handler execute when mouse move.

image

### PR DESCRIPTION
**Pull request by sohee-lee7**
When mousedown event occurs, mouseover event handler is registered
regardless of selection of table. So many mouseover event handlers
are registered.

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

fix #473 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/wwTableSelectionManager.js [hunk 1]
```diff
@@ -151,11 +151,13 @@ class WwTableSelectionManager {
...
-        this.setTableSelectionTimerIfNeed(selectionStart);
-        this.eventManager.listen('mouseover.tableSelection', onMouseover);
-        this.eventManager.listen('mouseup.tableSelection', onMouseup);
-        if (this.onDragStart && selectionStart) {
-          this.onDragStart(selectionStart);
+        if (selectionStart) {
+          this.setTableSelectionTimerIfNeed(selectionStart);
+          this.eventManager.listen('mouseover.tableSelection', onMouseover);
+          this.eventManager.listen('mouseup.tableSelection', onMouseup);
+          if (this.onDragStart && selectionStart) {
```
Comment (dongwoo-kim) [inline src/js/wwTableSelectionManager.js]: 위에서 한 번 `selectionStart` 여부를 확인했으면 여기서는 안해도 되지 않을까요?

Comment (sohee-lee7) [reply src/js/wwTableSelectionManager.js]: 오호라 그렇네요?!.... 흠.. 괜시리.. 원래의 구현 의도 자체가 mouseover를 매번 등록하는 것이었나 싶기도 하네요;;
테스트 후 제거해보겠습니다.
