### PR TITLE
fix: disappear line break when pasting in wysiwyg (fix #481)

### LINKED ISSUE #481: remove line break when paste in wysiwyg (3MD)
## Version
v1.4.0

## Test Environment
Chrome

## Current Behavior
When paste text in Wysiwyg, line break was removed.
Below text is sample text for reproducing problem.

***
Paste Issue
This issue occur in Wysiwyg

**Bold Text**
Sample TEXT

AAAAABBBBB
***

After pasting in Wysiwyg, line break was removed.
image

## Expected Behavior
Wysiwyg should maintain line break.

### PR DESCRIPTION
**Pull request by sohee-lee7**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

fix #481

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/wwPasteContentHelper.js [hunk 1]
```diff
@@ -198,6 +211,14 @@ class WwPasteContentHelper {
         return;
       }
 
+      if (blockElement.lastChild && blockElement.lastChild.nodeName !== 'BR') {
+        $blockElement.append(document.createElement('br'));
+      }
+
+      if (tagName === 'P' && !this._hasOnlyBR(blockElement)) {
+        $blockElement.append(document.createElement('br'));
+      }
```
Comment (junghwan-park) [inline src/js/wwPasteContentHelper.js]: 위와 아래 두번 만족해서 `BR`이 두번 생성되는 경우도 있는거죠? 그래도 괜찮은가요?

Comment (sohee-lee7) [reply src/js/wwPasteContentHelper.js]: 네, 의도적으로 `<p>` 사이에 `<br>`을 추가하려는 코드입니다.
